### ISSUE TITLE
Backwards-incompatible API changes should increment version number

### ISSUE THREAD

**Issue by maxhawkins** [JMongol/twilio-test-toolkit#2]
Commits 0d4ee8353f94f05060857993538d4b3977fabfa5 and e2d36a698dacd80ec0cb0d086deb6755bd423025 introduce backwards-incompatible API changes.

According to [semver](http://semver.org/) this means you should increment the version number to 2.0.0 or else make the changes backwards-compatible and increment to 1.1.0.

These changes caused problems for me because I specify ttt's version with '~> 1.0.0' in my gemfile. That means when I updated my bundle it automatically updated to the new, incompatible version and broke my build.

Please revert the backwards-incompatible changes or increment the version number to 2.0.0 to alert users of the change. Thanks!

**Comment by JMongol** [comment]
You're right - sorry about that. I just pushed a fix for this. I'll push a new build of the gem up to rubygems as well when they come back online.
